version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: respy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - respy-network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: respyadmin
      MINIO_ROOT_PASSWORD: respyproject
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - respy-network

  respy-app:
    container_name: respy-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    networks:
      - respy-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: respy_package_manager

networks:
  respy-network:
    driver: bridge
