version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: repsy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - repsy-network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: repsyadmin
      MINIO_ROOT_PASSWORD: repsyproject
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - repsy-network

  repsy-app:
    container_name: repsy-app
    image: repo.repsy.io/oguzhansandi/repsy-package-manager:latest   # 👈 build yerine image yazıyoruz
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    networks:
      - repsy-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

networks:
  repsy-network:
    driver: bridge
